### ISSUE TITLE
Dependency Problem?

### ISSUE THREAD

**Issue by stoneburner** [TICESoftware/DoubleRatchet#2]
Hi

i would like to experiment with your library, so i created a new single view ios project with the current version of XCode (11.4.1) and added this repo to the swift package manager.

everything was fetched correctly, but if i try to build the project i get "sodium.h file not found"

i tried to install libsodium like suggested with homebrew but that did not solve the problem

<img width="1120" alt="Screenshot 2020-05-18 at 12 22 56" src="https://user-images.githubusercontent.com/131283/82202806-bbebd280-9902-11ea-822d-3dbca536d582.png">

**Comment by FabioTacke** [comment]
Hi! 
That's because the compiler doesn't know where to find the libsodium library. You need to include the sodium.h header file in the header search path and link the binary framework of libsodium with your project.

When using the command line you can do it like this:
`swift build -Xcc -I[header search path] -Xlinker -L[binary path]`

In Xcode you can edit the header search path in "Build Settings" and add the framework (e. g. an .a file) in the "General" tab.

Although I think it should be possible to integrate libsodium installed via Homebrew you can try downloading a pre-compiled version of libsodium from their website and put that into your project root directory. Then you should be able to build (and run) the project like this:
`swift build -Xcc -Ilibsodium/include -Xlinker -Llibsodium/lib`.

I hope this helps.

**Comment by stoneburner** [comment]
thanks, awesome reply - will try adding the header search path

**Comment by stoneburner** [comment]
I added` libsodium.a` to the frameworks, copied the entire `libsodium` folder to the root of my project, added the include folder from that folder into my header search paths, but there is no change, "sodium.h" is still not found.

<img width="935" alt="Screenshot 2020-05-18 at 16 47 17" src="https://user-images.githubusercontent.com/131283/82227100-9cb36c00-9927-11ea-9cf5-1ac1db4957c6.png">
<img width="376" alt="Screenshot 2020-05-18 at 16 47 38" src="https://user-images.githubusercontent.com/131283/82227118-a1782000-9927-11ea-9f5a-a4974017536b.png">

It looks like that not my project is missing the header, but the Clibsodium framework?

<img width="1105" alt="Screenshot 2020-05-18 at 16 50 35" src="https://user-images.githubusercontent.com/131283/82227187-b3f25980-9927-11ea-90ba-307517ddaad9.png">

**Comment by FabioTacke** [comment]
If you add the path to the "include" directory to the *project's* build settings > header search path it should be fine because the targets inherit the search path from the project.
The binary framework (libsodium.a) should be added to the Sodium target's frameworks section.

I just checked that everything is working by doing the following steps:

1. Clone the repo and `cd` into the project directory.
2. Execute `swift package generate-xcodeproj`.
3. Copy the entire libsodium directory (in my case "libsodium-osx") into the project's root directory.
4. Open the generated project file with Xcode.
5. Add the path to the directory containing the libsodium header files to the *project's* header search path (see screenshot).
6. Add the libsodium directory to my project so that it appears in the project navigator on the left.
7. Drag the libsodium.a into the *Sodium target's* Frameworks and Libraries section (see screenshot).

The project builds successfully.

Maybe you can try those steps yourself in order to make sure that it's working and after that you can try to find out what's different in your previous project setup. Looks like you've created a new workspace and imported the files?

<img width="1342" alt="screenshot_1" src="https://user-images.githubusercontent.com/7275167/82230585-32e99100-992c-11ea-86ef-32bf8ad5756b.png">
<img width="1247" alt="screenshot_2" src="https://user-images.githubusercontent.com/7275167/82230588-341abe00-992c-11ea-8d4c-83abe12b46a4.png">

**Comment by stoneburner** [comment]
thanks, that worked (i also had to change the targets to ios and use libsodium-ios), the tests run thru without issues!

what i initially tried was to use this library with the swift package manager, i assumed that i could just add it to an ios project using the swift package manager in XCode.

(which worked, but then the clibsodium framework was missing the includes)

many thanks!
